anancarv/python-artifactory

.github/workflows/check_code.yml, mypy.ini, pyartifactory/objects.py
This PR aims to improve the tests and checks run on this project. It includes:
- Using a github action matrix to test on multiple Python versions
- Make the package [PEP561](https://www.python.org/dev/peps/pep-0561/) compatible
Fixes #10 
Fixes #27
=> Improve tests

README.md
Group documentation : fix examples
=> docs: fix Group examples

pyartifactory/models/group.py, pyartifactory/objects.py, tests/test_groups.py
Add the list of users to the group information
Unit tests have been updated
=> Return users in group

pyartifactory/objects.py
This PR aims to fix an issue where artifacts downloaded on Windows got the wrong local path. This was caused by a split on "/", which broke when running on Windows, which uses "\" for separation. 
There is a risk for this to be breaking for users running on Windows as it changes where downloaded artifacts are stored. However, it will now be in line with how it is expected to work.
Tested using the existing unit-test suite, which had a failing test on Windows.
=> Fix errors in local path when downloading artifacts on Windows

.github/workflows/check_code.yml, .github/workflows/deploy.yml
The github actions were not working anymore because an upgrade of the  actions python and poetry was needed
=> Fix github actions

pyartifactory/models/repository.py
Add `conan, alpine, gitlfs & vagrant`in PackageTypeEnum 
Fixes #85
=> feat: add packages  in PackageTypeEnum

pyartifactory/models/repository.py
Add support for creating Cargo repositories
- Verified manually against a real Artifactory instance that creates a Cargo local repository
- No other tests were added or changed in accordance with the practices in this repo: I couldn't find tests that exercise specific package types.
=> Add support for creating Cargo repositories

poetry.lock, pyartifactory/models/repository.py
Added some fields to repository models: local, remote and virtual.  
Fixed a typo at field "bypassHeadRequests" in `RemoteRepository`.
Updated dependencies `poetry update`
=> Add missing fields to repository models

poetry.lock, pyartifactory/__init__.py, pyproject.toml
I also had to update the lock file by running: `poetry lock --no-update`
=> Bump version: 1.10.2 → 1.10.3

README.md, pyartifactory/models/artifact.py, pyartifactory/objects.py, tests/test_artifacts.py
Added a feature tp retrieve a recursive list of artifacts at a give *path*.
Closes: #94 
Once the general concept is approved, I will added automated unit-tests.
=> Added artifact listing

README.md
Description
This updates the Readme to include an example of setting or updating the properties of an Artifactory property.
Fixes #127  
=> Updated set and update properties example in the readme.

pyartifactory/models/repository.py
Add package type 'terraform' to PackageEnum to enable Terraform repository management.
- [x ] New feature (non-breaking change which adds functionality)
Local tests with IDEs debugging mode
=> add repo type 'terraform'

pyartifactory/models/permission.py
Some permissions are missing to the `PermissionEnum`. We need to add them for not having validation errors
Fixes #134
=> feat: add new permissions to PermissionEnum

.gitignore, pyartifactory/objects/artifact.py, pyartifactory/objects/group.py, pyartifactory/objects/permission.py, pyartifactory/objects/repository.py, pyartifactory/objects/user.py, pyproject.toml
=> fix: fix create local repository

pyartifactory/models/repository.py, pyproject.toml
=> fix: fix pydantic validation error when creating repo

pyartifactory/objects/artifact.py
This change encodes artifacts path in a way suitable for including as a part of a URL.
Downloading of artifacts with some characters (for instance a hash sign '#') didn't work.
- [YES] Bug fix (non-breaking change which fixes an issue)
- [YES] Download artifacts with '#' in the name
- [YES] My PR is ready for prime time! Otherwise use the ["Draft PR" feature](https://help.github.com/en/articles/about-pull-requests#draft-pull-requests)
- [YES] All commits have a correct title
- [NO] Readme has been updated
- [YES] Quality tests are green (see Codacy)
=> fix: encode artifact path as url

pyartifactory/models/user.py
Updates the response to match recent artifactory versions
Fixes #163 
```
from __future__ import annotations
from pyartifactory import Artifactory
from pyartifactory.models import FederatedRepository, LocalRepository
import requests
requests.packages.urllib3.disable_warnings() 
from pprint import pprint
art = Artifactory(
url="https://artifactory.qs.mydomain.de/artifactory",
auth=("admin", "xxxx"),
verify=False,
)
users = art.users.list()
pprint(users)
```
=> Fixes #163; Simple User response from artifactory changed

README.md, pyartifactory/models/auth.py, pyartifactory/objects/object.py, tests/test_object.py
Add possibility to set requests timeout
=> Add possibility to set requests timeout

LICENSE, pyproject.toml
* feat: Deploy Artifact by Checksum
* feat: Add huggingfaceml, swift, ansible and pub as valid packageTypes
=> Bump version: 2.4.2 → 2.5.0

README.md, pyartifactory/models/auth.py, pyartifactory/objects/artifactory.py, pyartifactory/objects/object.py
Add the possibility to authenticate using `access_token` and also `anonymously`
Fixes #133
Fixes #173 
=> feat: add possibility to authenticate using access_token & anonymously

pyartifactory/models/repository.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Add support for OCI package type, see [repository configuration](https://jfrog.com/help/r/jfrog-rest-apis/repository-configuration-json) for reference.
- All test suite, there is no test at this level (package type)
=> Add OCI package support
