anancarv/python-artifactory

- pyartifactory/__init__.py
- pyartifactory/models/repository.py
- pyproject.toml
This PR fixes the following issues:
* Make VirtualRepositoryResponse inherit from VirtualRepository instead of LocalRepository
* Overload Virtual & Remote repository models with rclass
Fixes #44 
> Fix virtual repo

- .github/workflows/check_code.yml
- .pre-commit-config.yaml
- README.md
- mypy.ini
- poetry.lock
- pyartifactory/__init__.py
- pyartifactory/models/__init__.py
- pyartifactory/models/repository.py
- pyartifactory/objects.py
- pylintrc
- pyproject.toml
- tests/test_repositories.py
Currently, depending of the repository type (local, virtual or remote), we have to use a specific methods **(get_local_repo, get_virtual_repo, update_remote_repo ...)**. This PR proposes global methods **(get_repo, create-repo, update_repo)** that do not bother anymore with the repo type.
Fixes #45
> Generic repo actions

- poetry.lock
- pyproject.toml
When installing pyartifactory from Pypi I could see that Pylint was pulled in the dependencies. I simply moved it to the dev dependencies to avoid downloading unnecessary deps in production.
> chore: make Pylint a dev dependency

- README.md
- mypy.ini
- pyartifactory/exception.py
- pyartifactory/models/__init__.py
- pyartifactory/models/artifact.py
- pyartifactory/objects.py
- tests/test_artifacts.py
Fix `artifacts.properties()` method, and add a `artifacts.info()` method that returns what the old `.properties()` returned.
Fixes #50
Unit tests have been added for the fixed `.properties()` method, for the new `.info()`, and fixed for methods depending on the old `.properties()` behavior.
> Fix properties method

- pyartifactory/models/user.py
- pyartifactory/objects.py
Some attributes (such as `lastLoggedIn` or `realm`) are read-only, so we
don't need to send them back. It also fixes #57 indirectly, because we
don't try to serialize the date anymore.
> fix: do not send read-only attributes when updating user

- mypy.ini
- poetry.lock
- pyartifactory/objects.py
- pyproject.toml
Stream artifacts when deploying instead of sending it multipart-encoded.
This also removes the dependency on requests_toolbelt, which was only used in this instance.
Fixes #60
- create a test archive: `zip -r venv.zip .venv`
- deploy it to Artifactory with the followind code:
<details>
```py
from pyartifactory import Artifactory
USER = "user"
PASSWORD = "password"
a = Artifactory("https://artifactory-instance.jfrog.io", (USER, PASSWORD))
a.artifacts.deploy("venv.zip", "generic-repo/venv-deployed.zip")
```
</details>
- download it from the Web UI, rename as `venv-deployed-ui.zip`
- download it from the code (`a.artifacts.download("generic-repo/venv-deployed.zip")`)
- confirm files are identical with `xxhsum venv*`
<details>
```
$ xxhsum venv* …
```
> fix: stream artifact when deploying instead of sending multipart-encoded

- pyartifactory/objects.py
- tests/test_artifacts.py
This PR allows the `art.artifacts.deploy()` and `art.artifacts.download()` methods to operate on directories recursively.
(one could argue that the existing docs don't explicitly talk about arguments types (file or directory),
would it should at least be in the release notes)
I ran all existing tests (obviously), and added a new test (`test_artifacts.py::test_download_folder_success`)
to make sure downloading a directory work.
I did not add a new test to verify directory uploads.
> Add support for recursive up- and downloads

- pyartifactory/objects.py
- tests/test_artifacts.py
If the artifact path started with forward-slash, "/", the
the local folder would miss the first character of the word.
e.g. /test would be saved as /est
> fix: bug causing first char of path to disappear

- pyartifactory/models/repository.py
- pyartifactory/objects.py
- pyartifactory/utils.py
SecretStr is not JSON serializable and is throwing exceptions for RemoteRepositories that require a password.
I've been using this library to create repositories for my Artifactory Instance. I started adding a RemoteRepository for docker and came upon this error that states: "Object of type SecretStr is not JSON serializable"
Steps to reproduce the behavior:
```python
from pyartifactory import Artifactory
from pyartifactory.models import RemoteRepository
url = <url to artifactory instance>
auth = (<username>, <password>)
remote_docker_repo_cfg = {
"key": "docker-remote",
"url": "https://registry-1.docker.io/",
"packageType": "docker",
"username": <dockerhub username>,
"password": <dockerhub_password>,
}
rt = Artifactory(url=url, auth=auth)
remote_repo = …
```
> Removing SecretStr from RemoteRepository model

- pyartifactory/objects.py
- tests/test_repositories.py
Improve the typing of the functions `create_repo` and `update_repo` by adding function overloading. This way, we can give to the same function multiple type annotations to more accurately describe the function's behavior.
> feat: add overloading to create_repo & update_repo

- pyartifactory/objects.py
The documentation suggests that group names can be ", " delimited.
This works for group names that does not contain spaces.
Group names with spaces are supported.
To support this we must quote the group list, as `pyartifactory` does.
This also requires us to change group delimiter to ",".
I would assume this is due to Artifactory not being able to destinguish
between the delimiter space and any potential group name spaces.
Correct by using "," in combination with quoting the list.
> Correct member-of-groups usage for access tokens

- .gitignore
- README.md
- pyartifactory/__init__.py
- pyartifactory/artifactory_object.py
- pyartifactory/models/__init__.py
- pyartifactory/models/auth.py
- pyartifactory/models/permission.py
- pyartifactory/objects.py
- pyproject.toml
- tests/test_permissions.py
The V2 REST APIs apply for Artifactory version 6.6.0
and above, the user can pass the version explicitly.
Currently this only affects Permissions.
The permission scheme has changed in new version of artifactory, I had to find a way to behave based on API version supported by the server. 
Trying dynamic check of the server version I ended up in 5-6 server calls for each class that was called in class Artifactory.__init__
So At the end I opted for adding an argument that can be send to the constructor at the time the class is instantiated 
https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API+V2
I turned of the complexity fail on number of arguments, as all the ways around it would add more complexity. but I'm open to suggestions.  …
> Support Artifactory REST APIv2

- README.md
- pyartifactory/__init__.py
- pyartifactory/models/permission.py
- pyproject.toml
- tests/test_permissions.py
The PermissionV2 feature is not complete. Indeed, the objects build and releaseBundle are missing and if you update an existing permission which has both "repo" and "build" but don't set one or the other, the corresponding sub-permission is removed.
> feat: add build and releaseBundle to PermissionV2

- pyartifactory/models/repository.py
Add xrayIndex attribute to Class RemoteRepository to enable the xrayIndex option when creating a remote repository.
Added a default attribute to Class RemoteRepository to fix the following issue:
Fixes #96 
env: windows 10, python 3.7
Tested creating a remote repository using following codes:
```pyhton
remote_repo = RemoteRepository(key="test-1", url="https://registry.npmjs.org", packageType="npm", xrayIndex=True)
new_remote_repo = art.repositories.create_repo(remote_repo)
```
Checked in the jfrog GUI and the newly created remote repo "test-1" has enabled "Enable Indexing In Xray".
- [√] My PR is ready for prime time! Otherwise use the ["Draft PR" feature](https://help.github.com/en/articles/about-pull-requests#draft-pull-requests)
- [√] All …
> update RemoteRepository attribute

- pyartifactory/models/repository.py
This change flattens the `RemoteRepository` model and removes the `Nuget` repository model. The attributes of the `Nuget` repository have been moved to the `RemoteRepository` model. When JSON encoded, this model is in a structure that is expected by the Artifactory API when making calls to create/update a `RemoteRepository` of type `NuGet`. 
Fixes #106 
> Remove Nuget repo model and flatten RemoteRepository model

- pyartifactory/models/repository.py
metadataRetrievalTimeoutSecs: int = 60
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
> Add property to RemoteRepository

- README.md
- pyartifactory/artifactory_object.py
- pyartifactory/exception.py
- pyartifactory/objects.py
- tests/test_artifacts.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #91 
Tested manually with Artifactory 7:
As the API calls used do not return any data other than the HTTP status code, I'm not sure what's the proper approach to automated testing.
> Support for setting artifact properties

- poetry.lock
- pyproject.toml
The typing_extensions version used is way to old and it's conflicting to other libs.
Ran all unit tests
> Update typing_extensions lib

- pyartifactory/__init__.py
- pyproject.toml
Fix the dependency issue when install pyartifactory on python greater then 3.7
Fixes # (119)
- Bug fix (non-breaking change which fixes an issue)
- Version are resolved successfully on python 3.9 & python 3.8
> fix: dependency issue : typing_extensions

- pyartifactory/models/repository.py
Adds the projectKey param to BaseRepositoryModel to be able to create repos under a project.
> feat: allow specifying repository project key

- pyartifactory/models/repository.py
JFrog now supports [Sparse Indices for Cargo repositories](https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html) (see [API docs](https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON)). This is done through the `"cargoInternalIndex": "bool"` value.
These are stabilising on the 9th of March, so exposing these to automations will be useful.
I have smoketested this change against our local Artifactory.
- [X ] My PR is ready for prime time! Otherwise use the ["Draft PR" feature](https://help.github.com/en/articles/about-pull-requests#draft-pull-requests)
> Add cargoInternalIndex value for local-repos

- tests/test_artifacts.py
test_download_artifact_success fails on Windows because `ArtifactoryArtifact.as_posix` returns forward slashes, whereas the test expects backward ones.  Use `Path.as_posix` instead of `Path.resolve` in the test case to expect forward slashes instead.
Here's the test output without this change:
```
==================================================================================== FAILURES ====================================================================================
_________________________________________________________________________ test_download_artifact_success _________________________________________________________________________
tmp_path = WindowsPath('C:/Users/mkraai/AppData/Local/Temp/1/pytest-of-mkraai/pytest-4/test_download_artifact_success0')
@responses.activate …
```
> Fix test_download_artifact_success on Windows

- README.md
- pyartifactory/models/__init__.py
- pyartifactory/models/repository.py
- pyartifactory/objects/repository.py
- tests/test_repositories.py
Artifactory provides in a new Type of Repo: `federated`. this is basically a local repo, except that the model has a field members, which contains URLs to other artifactory instances and replicated (bi-directional) the content between these instances
-
```
from __future__ import annotations
from pyartifactory import Artifactory
from pyartifactory.models import FederatedRepository, LocalRepository
art = Artifactory(
url="https://URL/artifactory",
auth=("XXX", "XXX"),
verify=False,
)
local_repo = LocalRepository(key="local_test")
new_local_repo = art.repositories.create_repo(local_repo)
fed_repo = FederatedRepository(key="test2")
new_fed_repo = art.repositories.create_repo(fed_repo)
```
> Feature: Added federated repo type

- pyartifactory/models/repository.py
This PR added 2 repotypes to the library:
* helmoci
* terraformbackend
furthermore it added some typing validation for the terraform repository (`terraformType`), which is a mandatory parameter when adding a terraform repo
```
repo = LocalRepository(key="tf-be", packageType="terraformbackend")
newrepo = art.repositories.create_repo(repo)
repo = art.repositories.get_repo("tf-be")
pprint(repo)
art.repositories.delete("tf-be")
print("-----------------")
repo = LocalRepository(key="tf-module", packageType="terraform", terraformType="MODULE")
newrepo = art.repositories.create_repo(repo)
repo = …
```
> Added terraform backend and helmoci package types

- pyartifactory/objects/artifact.py
According  to the [documentation](https://jfrog.com/help/r/jfrog-rest-apis/update-item-properties), the recursive parameter should be "recursiveProperties" not "recursive". (Update api only)
https://jfrog.com/help/r/jfrog-rest-apis/update-item-properties
> Fix recursive parameter

- pyartifactory/objects/artifactory.py
I forgot to add the timeout parameter to the Artifactory class in my previous pull request. It was only added to the ArtifactoryObject constructor. As a result, we can't initialize an Artifactory instance with a timeout, and it must be set on the artifactory attribute after initialization. This PR adds the timeout parameter to the Artifactory init function, and the timeout should now be usable as described in the documentation.
sorry for the mistake.
No new unit test.
> Fix timeout: Add timeout parameter on Artifactory constructor too

- README.md
- pyartifactory/objects/repository.py
- pyproject.toml
When creating a repository with a password, this password is transmitted as stars only in the REST request:
"password": "**********"
Fixes #179
> fix: convert password to str for create_remote_repo

- README.md
- pyartifactory/objects/artifact.py
- tests/test_artifacts.py
Artifactory REST API supports deploying artifacts and properties in a single operation. This is particularly useful so that you don't have to make any additional API calls to set properties.
This PR enables the deployment of artifacts and properties (optional parameter) in the same request.
> Deploy properties along with artifacts

- README.md
- pyartifactory/objects/security.py
- tests/test_security.py
Support the new `/access/api/v1/tokens` REST API to create access tokens (See [documentation](https://jfrog.com/help/r/jfrog-rest-apis/create-token)).
The old Create Token API that is used by ArtifactorySecurity.create_access_token() is deprecated: https://jfrog.com/help/r/jfrog-rest-apis/create-token-deprecated
Tokens created using the old API can't be used to authenticate with the new API due to audience limitations in old tokens.
Fixes #150
> fix: support new create access token API

- pyartifactory/objects/artifactory.py
- pyproject.toml
v2.7.0 added a new parameter (access_token) in the middle of the Artifactory class constructor, breaking backward compatibility.
Fixes #197
> fix: re-order access_token param in Artifactory object

- README.md
- pyartifactory/exception.py
- pyartifactory/models/artifact.py
- pyartifactory/objects/artifact.py
- tests/test_artifacts.py
Artifactory UI shows a warning message in the uploaded artifacts when artifact checksums aren't provided, therefore we would like to push a checksum of binaries being deployed.
Pushing checksums doesn't seem to be a well documented feature in the JFrog documentation, however here is brief reference to it https://jfrog.com/help/r/why-am-i-getting-client-did-not-publish-a-checksum-value-for-npm-packages/why-am-i-getting-client-did-not-publish-a-checksum-value...-for-npm-packages
> Pass the artifacts checksums in the headers of the deploy request

- pyartifactory/models/artifact.py
Mark OriginalChecksums attrs as Optional. 
Fixes #210 
- [] Quality tests are green (see Codacy)
- [] Automated tests are green (see pipeline)
> Update models/artifact.py to set OriginalChecksums attribute as Optional

- pyartifactory/models/build.py
Before these changes, calling `art.builds.get_build_info(NAME, BUILD_NO)` would result in a validation error and exception
```
ValidationError: 2 validation errors for BuildInfo
buildInfo.modules.0.properties
Field required [type=missing, input_value={'id': 'PATH/TO/FILE}]}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.11/v/missing
buildInfo.modules.0.type
Field required [type=missing, input_value={'id': 'PATH/TO/FILE}]}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.11/v/missing
```
After these changes `art.builds.get_build_info(NAME, BUILD_NO)` returns a `BuildInfo` object that can be interacted with.
* Make properties and type optional for BuildModules
Neither field is listed as `required` in the buildinfo schema at …
> Fix validation error when trying to access build info

- pyartifactory/objects/artifact.py
Fix objects.artifact delete function docstring 
Fixes #207
> docs: edit artifact.delete docstring return type
